spring.application.name: coupon
spring.profiles.active: local

spring:
  config:
    import:
      - db.yml
      - redis.yml
      - monitoring.yml

---
spring.config.activate.on-profile: local

jwt:
  access-token:
    secret: ${jwt-local-access-secret}
    expire: 3600000

---
spring.config.activate.on-profile: prod

jwt:
  access-token:
    secret: ${jwt-prod-access-secret}
    expire: 3600000
